- hosts: webserver
  tasks:
  - name: build container image
    docker_image:
      name: democontainer:v1.0
      source: build
      build:
        path: /home/chrisotelios/docker-project
      state: present
    become: yes
    become_user: root