---
- hosts: all
  become: true
  tasks:
  # - name: Install packages that allow apt to be used over HTTPS
  #   apt:
  #     name: "{{ packages }}"
  #     state: present
  #     update_cache: yes
  #   vars:
  #     packages:
  #     - apt-transport-https
  #     - ca-certificates
  #     - curl
  #     - gnupg-agent
  #     - software-properties-common

  # - name: Add an apt signing key for Docker
  #   apt_key:
  #     url: https://download.docker.com/linux/ubuntu/gpg
  #     state: present

  # - name: Add apt repository for stable version
  #   apt_repository:
  #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
  #     state: present

  # - name: Install docker and its dependecies
  #   apt: 
  #     name: "{{ packages }}"
  #     state: present
  #     update_cache: yes
  #   vars:
  #     packages:
  #     - docker-ce 
  #     - docker-ce-cli 
  #     - containerd.io
  #   notify:
  #     - docker status

  # - name: Add vagrant user to docker group
  #   user:
  #     name: chrisotelios
  #     group: docker
      
  #  - name: Remove swapfile from /etc/fstab
  #     mount:
  #       name: "{{ item }}"
  #       fstype: swap
  #       state: absent
  #     with_items:
  #       - swap
  #       - none

  #  - name: Disable swap
  #   command: swapoff -a
  #   when: ansible_swaptotal_mb > 0
    
  - name: Install Microk8s
    hosts: localhost
    gather_facts: false
    become: true
    tasks:
      - name: Install docker
        apt:
          name: docker.io
          update_cache: true
          cache_valid_time: 86400
          state: present
      - name: Install microk8s
        snap:
          name: microk8s
          state: present
        classic: yes

      - name: Add user to Docker and Microk8s groups, they will need to logout and in again
        user:
          name: '{{ lookup("env", "USER") }}'
          state: present
          groups:
            - docker
            - microk8s
          append: true
      - name: Add alias to kubectl
        become: false
        lineinfile:
          path: '{{ lookup("env", "HOME") }}/.bashrc'
          regexp: '^alias kubectl='
          line: 'alias kubectl="microk8s kubectl"'
          state: present
      - name: Add bash completion for kubectl
        become: false
        lineinfile:
          path: '{{ lookup("env", "HOME") }}/.bashrc'
        regexp: '^source \<\(kubectl'
        line: 'source <(kubectl completion bash)'
        state: present