---
- hosts: all
  become: true
  tasks:
  
  - name: install MicroK8s
    become: True
    become_user: root
    shell:
      cmd: "snap install microk8s --classic"

  - name: install Kubectl
    become: True
    become_user: root
    shell:
      cmd: "snap install kubectl --classic"

  - name: enable ingress
    become: True
    become_user: root
    shell:
      cmd: "microk8s.enable dashboard dns storage ingress"

  - name: access microk8s without sudo
    become: True
    become_user: root
    shell:  
      cmd: |
            sudo usermod -a -G microk8s $USER 
            sudo chown -f -R $USER ~/.kube 

  - name: cli
    become: True
    become_user: root
    shell:
      cmd: "curl -sS https://webinstall.dev/k9s | bash"

  - name: setup config
    become: True
    become_user: root
    shell:
      cmd: "microk8s.kubectl config view --raw > $HOME/.kube/config"


  - name: apply kubctl yaml files
    become: True
    become_user: root
    shell:
      chdir: /home/chrisotelios/devops-kubernetes
      cmd: |
            kubectl apply -f app-deployment.yaml
            kubectl apply -f app-service.yaml
            kubectl apply -f app-ingress.yaml
