---
- hosts: all
  become: true
  vars:
    app_dir: "{{user_dir}}/kubernetes-project"
    git_repo_url: "https://github.com/clamprou/devops-kubernetes.git"
    git_repo_branch: "master"
  tasks:
  
  - name: install MicroK8s
    become: True
    become_user: root
    shell:
      cmd: "snap install microk8s --classic"

  - name: install Kubectl
    become: True
    become_user: root
    shell:
      cmd: "snap install kubectl --classic"

  - name: enable ingress
    become: True
    become_user: root
    shell:
      cmd: "microk8s.enable dashboard dns storage ingress"

  - name: access microk8s without sudo
    become: True
    become_user: root
    shell:  
      cmd: |
            sudo usermod -a -G microk8s $USER 
            sudo chown -f -R $USER ~/.kube 

  - name: cli
    become: True
    become_user: root
    shell:
      cmd: "curl -sS https://webinstall.dev/k9s | bash"

  - name: setup config
    become: True
    become_user: root
    shell:
      cmd: "microk8s.kubectl config view --raw > $HOME/.kube/config"
      
  - name: ensure github.com is a known host
    lineinfile:
      dest: "{{user_dir}}/.ssh/known_hosts"
      create: yes
      state: present
      line: "{{lookup('pipe', 'ssh-keyscan -t rsa github.com')}}"
      regexp: "^github\\.com"
    ignore_errors: true

  - name: clone kubernetes project
    git:
      repo: "{{git_repo_url}}"
      version: "{{git_repo_branch}}"
      clone: yes
      force: yes
      dest: "{{app_dir}}"
    changed_when: true

  - name: apply kubctl yaml files
    become: True
    become_user: root
    shell:
      chdir: "{{app_dir}}"
      cmd: |
            kubectl apply -f app-deployment.yaml
            kubectl apply -f app-service.yaml
            kubectl apply -f app-ingress.yaml
