---
- hosts: database
  roles:
    - role: geerlingguy.postgresql
      become: yes
  tasks:
    - name: change listen_addresses to '*'
      lineinfile:
        dest: /etc/postgresql/10/main/postgresql.conf
        regexp: "^#listen_addresses"
        line: "listen_addresses = '*'"
        state: present
        backup: yes
      become: yes
      notify:
        - restart postgresql

    - name: Insert query to test_table in db test_db
      community.postgresql.postgresql_query:
        db: demodb
        query: INSERT INTO users_myuser VALUES (2,'pbkdf2_sha256$180000$jspFOqq1G0Uj$WYR2sUVZW07WLxRBw8wdxVWq0+e2uShlRMrOdG4cAFo=','2022-06-29 19:44:38.977579+03',true,'asd','asd','asd','chrisotelios@gmail.com',true,true,'2022-06-29 19:42:28.314074+03',false,true);
      
  tags:
    - postgres
  vars:
    postgresql_databases:
      - name: demodb
    postgresql_users:
      - name: demouser
        password: pass123
    postgresql_locales:
      - 'en_US.UTF-8'
    postgresql_hba_entries:
      - { type: local, database: all, user: postgres, auth_method: peer }
      - { type: local, database: all, user: all, auth_method: peer }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
      - { type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5 }
      - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
